# Generated by Django 4.0.7 on 2022-12-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tanlov', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
