# Generated by Django 4.0.7 on 2022-12-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_toppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('content', models.TextField(verbose_name='mazmun')),
                ('tanlov', models.CharField(max_length=20, verbose_name='tanlov')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('image', models.CharField(max_length=255, verbose_name='rasm')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='mazmun'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=255, verbose_name='rasm'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tanlov',
            field=models.CharField(max_length=20, verbose_name='tanlov'),
        ),
        migrations.AlterField(
            model_name='toppost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vaqt'),
        ),
        migrations.AlterField(
            model_name='toppost',
            name='image',
            field=models.CharField(max_length=255, verbose_name='rasm'),
        ),
        migrations.AlterField(
            model_name='toppost',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='toppost',
            name='tanlov',
            field=models.CharField(max_length=20, verbose_name='tanlov'),
        ),
    ]
